dist: xenial
language: node_js
node_js:
  - "11"
cache:
  apt: true
  npm: true
before_install:
  - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - echo "deb http://www.apache.org/dist/cassandra/debian 311x main" |
    sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - sudo apt-get update
  - sudo apt-get install cassandra
  - sudo service cassandra start
  - sudo netstat -lntp
